jobs:
  ci:
    name: Ci
    runs-on: ubuntu-20.04

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Get Dependencies
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Tests
        run: ./ci/test

name: Check

on:
  schedule:
    - cron: "45 */2 * * *"
